spring:
  application:
    name: ComercialCardPTM
  datasource:
    url: jdbc:mysql://localhost:3306/crud_app
    username: root
    password: Abcd1234*
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
